### ISSUE TITLE
Pandas DataFrame with aggregated information

### ISSUE THREAD

**Issue by bastinat0r** [ovgu-FINken/driving_swarm_infrastructure#21]
Spalten: zeit, roboter-name, x-velocity, theta-velocity, x, y, theta, min(range), travelled distance, _erreichte ziele_

**Comment by ntraichel** [comment]
How to create Jupyter Notebook in virtualvenv: https://medium.com/@eleroy/jupyter-notebook-in-a-virtual-environment-virtualenv-8f3c3448247

**Comment by ntraichel** [comment]
Using jupyter-ros2: https://github.com/zmk5/jupyter-ros2

If you receive an error at line `jupyter nbextension enable --py --sys-prefix ipywidgets` 
 --> use `jupyter nbextension enable --py --sys-prefix widgetsnbextension` instead (see https://github.com/zmk5/jupyter-ros2/issues/4)

**Comment by joeldierkes** [comment]
New features:
- [ ] If no new data from [timestamp - 1, timestamp] is available then fill cell with NaN
