### ISSUE TITLE
(Semi-)Automate SD-Card Duplication

### ISSUE THREAD

**Issue by bastinat0r** [ovgu-FINken/driving_swarm_infrastructure#3]

**Comment by joeldierkes** [comment]
network.target ist nicht das wofür man es hält...
https://www.freedesktop.org/wiki/Software/systemd/NetworkTarget/

https://github.com/ovgu-FINken/driving_swarm_sd_writer/blob/98776afffdec1d86a09919207207f0222a824db8/overlay/etc/systemd/system/firstrun.service#L3
